import { Prisma } from '@prisma/client'

/**
 * Veritabanı boşken eklenecek varsayılan telaffuz kelimeleri.
 * Bu veri iş mantığına (PronunciationService) değil, seed katmanına aittir (SRP).
 */
export const DEFAULT_PRONUNCIATION_WORDS: Prisma.PronunciationWordCreateInput[] = [
  // DevOps & Cloud
  { word: 'Kubernetes',       category: 'DevOps',        phonetic: 'koo-ber-NET-eez' },
  { word: 'infrastructure',   category: 'DevOps',        phonetic: 'IN-fra-struk-chur' },
  { word: 'containerization', category: 'DevOps',        phonetic: 'kun-tay-ner-ih-ZAY-shun' },
  { word: 'orchestration',    category: 'DevOps',        phonetic: 'or-keh-STRAY-shun' },
  { word: 'serverless',       category: 'Cloud',         phonetic: 'SUR-ver-less' },
  { word: 'virtualization',   category: 'Cloud',         phonetic: 'vur-choo-uh-lih-ZAY-shun' },
  { word: 'provisioning',     category: 'DevOps',        phonetic: 'pro-VIZH-uh-ning' },
  { word: 'observability',    category: 'DevOps',        phonetic: 'ob-zur-vuh-BIL-ih-tee' },
  { word: 'telemetry',        category: 'DevOps',        phonetic: 'teh-LEM-eh-tree' },
  { word: 'immutable',        category: 'DevOps',        phonetic: 'ih-MYOO-tuh-bul' },
  { word: 'continuous',       category: 'DevOps',        phonetic: 'kun-TIN-yoo-us' },
  { word: 'integration',      category: 'DevOps',        phonetic: 'in-teh-GRAY-shun' },
  { word: 'deployment',       category: 'DevOps',        phonetic: 'dee-PLOY-ment' },
  { word: 'hypervisor',       category: 'Cloud',         phonetic: 'HY-per-vy-zer' },
  { word: 'elasticity',       category: 'Cloud',         phonetic: 'ih-las-TIS-ih-tee' },
  { word: 'multi-tenant',     category: 'Cloud',         phonetic: 'MUL-tee-TEN-unt' },
  
  // Database & Storage
  { word: 'PostgreSQL',       category: 'Database',      phonetic: 'POST-gres-Q-L' },
  { word: 'NoSQL',            category: 'Database',      phonetic: 'no-SEE-kwul' },
  { word: 'sharding',         category: 'Database',      phonetic: 'SHAR-ding' },
  { word: 'indexing',         category: 'Database',      phonetic: 'IN-deks-ing' },
  { word: 'relational',       category: 'Database',      phonetic: 'rih-LAY-shun-ul' },
  { word: 'normalization',    category: 'Database',      phonetic: 'nor-muh-lih-ZAY-shun' },
  { word: 'transaction',      category: 'Database',      phonetic: 'tran-ZAK-shun' },
  { word: 'isolation',        category: 'Database',      phonetic: 'eye-suh-LAY-shun' },
  { word: 'consistency',      category: 'Database',      phonetic: 'kun-SIS-ten-see' },
  { word: 'durability',       category: 'Database',      phonetic: 'doo-ruh-BIL-ih-tee' },
  { word: 'replication',      category: 'Database',      phonetic: 'rep-lih-KAY-shun' },
  { word: 'aggregation',      category: 'Database',      phonetic: 'ag-rih-GRAY-shun' },
  { word: 'schema',           category: 'Database',      phonetic: 'SKEE-muh' },
  { word: 'foreign key',      category: 'Database',      phonetic: 'FOR-in kee' },
  { word: 'denormalization',  category: 'Database',      phonetic: 'dee-nor-muh-lih-ZAY-shun' },
  
  // Programming & OOP
  { word: 'asynchronous',     category: 'Programming',   phonetic: 'ay-SINK-ruh-nus' },
  { word: 'algorithm',        category: 'Programming',   phonetic: 'AL-go-rith-um' },
  { word: 'deprecated',       category: 'Programming',   phonetic: 'DEP-ruh-kay-ted' },
  { word: 'recursion',        category: 'Programming',   phonetic: 'reh-KUR-zhun' },
  { word: 'polymorphism',     category: 'OOP',           phonetic: 'pol-ee-MOR-fiz-um' },
  { word: 'synchronization',  category: 'Programming',   phonetic: 'sin-kruh-nih-ZAY-shun' },
  { word: 'refactoring',      category: 'Programming',   phonetic: 'ree-FAK-tor-ing' },
  { word: 'encapsulation',    category: 'OOP',           phonetic: 'en-kap-syoo-LAY-shun' },
  { word: 'concatenate',      category: 'Programming',   phonetic: 'kon-KAT-en-ayt' },
  { word: 'instantiation',    category: 'OOP',           phonetic: 'in-stan-shee-AY-shun' },
  { word: 'inheritance',      category: 'OOP',           phonetic: 'in-HAIR-ih-tuns' },
  { word: 'concurrency',      category: 'Programming',   phonetic: 'kun-KUR-en-see' },
  { word: 'abstraction',      category: 'OOP',           phonetic: 'ab-STRAK-shun' },
  { word: 'interface',        category: 'OOP',           phonetic: 'IN-ter-fays' },
  { word: 'constructor',      category: 'OOP',           phonetic: 'kun-STRUK-ter' },
  { word: 'closure',          category: 'Programming',   phonetic: 'KLOH-zhur' },
  { word: 'callback',         category: 'Programming',   phonetic: 'KAWL-bak' },
  { word: 'parameter',        category: 'Programming',   phonetic: 'puh-RAM-ih-ter' },
  { word: 'variable',         category: 'Programming',   phonetic: 'VAIR-ee-uh-bul' },
  { word: 'boolean',          category: 'Programming',   phonetic: 'BOO-lee-un' },
  
  // Architecture & Backend
  { word: 'microservices',    category: 'Architecture',  phonetic: 'MY-kro-SUR-vi-sez' },
  { word: 'middleware',       category: 'Backend',       phonetic: 'MID-ul-wair' },
  { word: 'scalability',      category: 'Architecture',  phonetic: 'skay-luh-BIL-ih-tee' },
  { word: 'idempotent',       category: 'API',           phonetic: 'eye-DEM-poh-tent' },
  { word: 'monolithic',       category: 'Architecture',  phonetic: 'mah-nuh-LITH-ik' },
  { word: 'caching',          category: 'Backend',       phonetic: 'KASH-ing' },
  { word: 'GraphQL',          category: 'API',           phonetic: 'graf-Q-L' },
  { word: 'RESTful',          category: 'API',           phonetic: 'REST-ful' },
  { word: 'webhook',          category: 'API',           phonetic: 'WEB-hook' },
  { word: 'endpoint',         category: 'API',           phonetic: 'END-poynt' },
  { word: 'stateless',        category: 'Architecture',  phonetic: 'STAYT-les' },
  { word: 'proxy',            category: 'Network',       phonetic: 'PROK-see' },
  { word: 'load balancer',    category: 'Architecture',  phonetic: 'lohd BAL-un-ser' },
  { word: 'gateway',          category: 'Architecture',  phonetic: 'GAYT-way' },
  { word: 'websockets',       category: 'Backend',       phonetic: 'WEB-sok-its' },
  
  // Security
  { word: 'authentication',   category: 'Security',      phonetic: 'aw-then-tih-KAY-shun' },
  { word: 'authorization',    category: 'Security',      phonetic: 'aw-thor-ih-ZAY-shun' },
  { word: 'cryptography',     category: 'Security',      phonetic: 'krip-TOG-ruh-fee' },
  { word: 'vulnerability',    category: 'Security',      phonetic: 'vul-ner-uh-BIL-ih-tee' },
  { word: 'encryption',       category: 'Security',      phonetic: 'en-KRIP-shun' },
  { word: 'malware',          category: 'Security',      phonetic: 'MAL-wair' },
  { word: 'phishing',         category: 'Security',      phonetic: 'FISH-ing' },
  { word: 'ransomware',       category: 'Security',      phonetic: 'RAN-sum-wair' },
  { word: 'penetration',      category: 'Security',      phonetic: 'pen-ih-TRAY-shun' },
  { word: 'firewall',         category: 'Security',      phonetic: 'FY-er-wawl' },
  { word: 'certificates',     category: 'Security',      phonetic: 'ser-TIF-ih-kits' },
  { word: 'salting',          category: 'Security',      phonetic: 'SAWL-ting' },
  { word: 'hashing',          category: 'Security',      phonetic: 'HASH-ing' },
  { word: 'privilege',        category: 'Security',      phonetic: 'PRIV-uh-lij' },
  
  // Network
  { word: 'bandwidth',        category: 'Network',       phonetic: 'BAND-width' },
  { word: 'throughput',       category: 'Network',       phonetic: 'THROO-put' },
  { word: 'latency',          category: 'Network',       phonetic: 'LAY-tun-see' },
  { word: 'protocol',         category: 'Network',       phonetic: 'PRO-tuh-kol' },
  { word: 'handshake',        category: 'Network',       phonetic: 'HAND-shayk' },
  { word: 'packet',           category: 'Network',       phonetic: 'PAK-it' },
  { word: 'routing',          category: 'Network',       phonetic: 'ROW-ting' },
  { word: 'subnet',           category: 'Network',       phonetic: 'SUB-net' },
  { word: 'topology',         category: 'Network',       phonetic: 'tuh-POL-uh-jee' },
  { word: 'multiplexing',     category: 'Network',       phonetic: 'MUL-tih-plek-sing' },
  
  // Git & Version Control
  { word: 'repository',       category: 'Git',           phonetic: 'reh-POZ-ih-tor-ee' },
  { word: 'merge',            category: 'Git',           phonetic: 'murj' },
  { word: 'conflict',         category: 'Git',           phonetic: 'KON-flikt' },
  { word: 'branching',        category: 'Git',           phonetic: 'BRANCH-ing' },
  { word: 'commit',           category: 'Git',           phonetic: 'kuh-MIT' },
  { word: 'rebase',           category: 'Git',           phonetic: 'REE-bays' },
  { word: 'cherry-pick',      category: 'Git',           phonetic: 'CHAIR-ee-pik' },
  { word: 'stash',            category: 'Git',           phonetic: 'stash' },
  { word: 'upstream',         category: 'Git',           phonetic: 'UP-streem' },
  { word: 'submodule',        category: 'Git',           phonetic: 'SUB-mod-yool' },
  
  // Frontend
  { word: 'component',        category: 'Frontend',      phonetic: 'kum-POH-nent' },
  { word: 'responsive',       category: 'Frontend',      phonetic: 'rih-SPON-siv' },
  { word: 'accessibility',    category: 'Frontend',      phonetic: 'ak-ses-ih-BIL-ih-tee' },
  { word: 'hydration',        category: 'Frontend',      phonetic: 'hy-DRAY-shun' },
  { word: 'framework',        category: 'Frontend',      phonetic: 'FRAYM-wurk' },
  { word: 'declarative',      category: 'Frontend',      phonetic: 'dih-KLAIR-uh-tiv' },
  { word: 'statefulness',     category: 'Frontend',      phonetic: 'STAYT-ful-nes' },
  { word: 'bundler',          category: 'Frontend',      phonetic: 'BUN-dler' },
  { word: 'transpiler',       category: 'Frontend',      phonetic: 'trans-PY-ler' },
  { word: 'polyfill',         category: 'Frontend',      phonetic: 'POL-ee-fil' },
  { word: 'DOM',              category: 'Frontend',      phonetic: 'dom' },
  { word: 'minification',     category: 'Frontend',      phonetic: 'min-ih-fih-KAY-shun' },
  { word: 'debounce',         category: 'Frontend',      phonetic: 'dee-BOWNS' },
  { word: 'throttle',         category: 'Frontend',      phonetic: 'THROT-ul' },
  { word: 'typography',       category: 'Frontend',      phonetic: 'ty-POG-ruh-fee' },
  
  // Data Science & AI
  { word: 'machine learning', category: 'AI',            phonetic: 'muh-SHEEN LUR-ning' },
  { word: 'neural network',   category: 'AI',            phonetic: 'NOOR-ul NET-wurk' },
  { word: 'tensor',           category: 'AI',            phonetic: 'TEN-ser' },
  { word: 'dataset',          category: 'Data',          phonetic: 'DAY-tuh-set' },
  { word: 'variance',         category: 'Data',          phonetic: 'VAIR-ee-uns' },
  { word: 'heuristic',        category: 'AI',            phonetic: 'hyoo-RIS-tik' },
  { word: 'classification',   category: 'AI',            phonetic: 'klas-ih-fih-KAY-shun' },
  { word: 'regression',       category: 'Data',          phonetic: 'rih-GRESH-un' },
  { word: 'clustering',       category: 'AI',            phonetic: 'KLUS-ter-ing' },
  { word: 'hyperparameter',   category: 'AI',            phonetic: 'hy-per-puh-RAM-ih-ter' },
  { word: 'backpropagation',  category: 'AI',            phonetic: 'bak-prop-uh-GAY-shun' },
  { word: 'generative',       category: 'AI',            phonetic: 'JEN-er-uh-tiv' },
  { word: 'inference',        category: 'AI',            phonetic: 'IN-fer-uns' },
  { word: 'embedding',        category: 'AI',            phonetic: 'em-BED-ing' },
  { word: 'tokenization',     category: 'AI',            phonetic: 'toh-ken-ih-ZAY-shun' },
  
  // System Design
  { word: 'quorum',           category: 'System Design', phonetic: 'KWOR-um' },
  { word: 'bottleneck',       category: 'System Design', phonetic: 'BOT-ul-nek' },
  { word: 'distributed',      category: 'System Design', phonetic: 'dih-STRIB-yoo-ted' },
  { word: 'partitioning',     category: 'System Design', phonetic: 'par-TISH-uh-ning' },
  { word: 'consensus',        category: 'System Design', phonetic: 'kun-SEN-sus' },
  { word: 'pagination',       category: 'System Design', phonetic: 'paj-ih-NAY-shun' },
  { word: 'resilience',       category: 'System Design', phonetic: 'rih-ZIL-yuns' },
  { word: 'availability',     category: 'System Design', phonetic: 'uh-vay-luh-BIL-ih-tee' },
  { word: 'redundancy',       category: 'System Design', phonetic: 'rih-DUN-dun-see' },
  { word: 'monolith',         category: 'System Design', phonetic: 'MON-uh-lith' },
  
  // Mobile & Native
  { word: 'emulator',         category: 'Mobile',        phonetic: 'EM-yuh-lay-ter' },
  { word: 'simulator',        category: 'Mobile',        phonetic: 'SIM-yuh-lay-ter' },
  { word: 'native',           category: 'Mobile',        phonetic: 'NAY-tiv' },
  { word: 'cross-platform',   category: 'Mobile',        phonetic: 'kros-PLAT-form' },
  { word: 'gradle',           category: 'Mobile',        phonetic: 'GRAY-dul' },
  { word: 'composable',       category: 'Mobile',        phonetic: 'kum-POH-zuh-bul' },
  { word: 'permissions',      category: 'Mobile',        phonetic: 'per-MISH-unz' },
  { word: 'lifecycle',        category: 'Mobile',        phonetic: 'LYF-sy-kul' },
  
  // QA & Testing
  { word: 'assertion',        category: 'Testing',       phonetic: 'uh-SUR-shun' },
  { word: 'fixture',          category: 'Testing',       phonetic: 'FIKS-chur' },
  { word: 'mutation',         category: 'Testing',       phonetic: 'myoo-TAY-shun' },
  { word: 'coverage',         category: 'Testing',       phonetic: 'KUV-er-ij' },
  { word: 'mocking',          category: 'Testing',       phonetic: 'MOK-ing' },
  { word: 'stubbing',         category: 'Testing',       phonetic: 'STUB-ing' },
  { word: 'integration',      category: 'Testing',       phonetic: 'in-teh-GRAY-shun' },
  { word: 'usability',        category: 'Testing',       phonetic: 'yoo-zuh-BIL-ih-tee' },
  
  // Data Engineering
  { word: 'pipeline',         category: 'Data Eng',      phonetic: 'PYP-lyn' },
  { word: 'warehouse',        category: 'Data Eng',      phonetic: 'WAIR-hows' },
  { word: 'analytics',        category: 'Data Eng',      phonetic: 'an-uh-LIT-iks' },
  { word: 'visualization',    category: 'Data Eng',      phonetic: 'vizh-oo-uh-lih-ZAY-shun' },
  { word: 'map-reduce',       category: 'Data Eng',      phonetic: 'map rih-DOOS' },
  { word: 'dashboard',        category: 'Data Eng',      phonetic: 'DASH-bord' },
  { word: 'streaming',        category: 'Data Eng',      phonetic: 'STREE-ming' },
  
  // Core Computer Science
  { word: 'deadlock',         category: 'Computer Science', phonetic: 'DED-lok' },
  { word: 'semaphore',        category: 'Computer Science', phonetic: 'SEM-uh-for' },
  { word: 'mutex',            category: 'Computer Science', phonetic: 'MYOO-teks' },
  { word: 'pointer',          category: 'Computer Science', phonetic: 'POYN-ter' },
  { word: 'memory leak',      category: 'Computer Science', phonetic: 'MEM-uh-ree leek' },
  { word: 'heap',             category: 'Computer Science', phonetic: 'heep' },
  { word: 'stack',            category: 'Computer Science', phonetic: 'stak' },
  { word: 'queue',            category: 'Computer Science', phonetic: 'kyoo' },
  { word: 'linked list',      category: 'Computer Science', phonetic: 'linkt list' },
  { word: 'binary tree',      category: 'Computer Science', phonetic: 'BY-nuh-ree tree' },
  { word: 'hash map',         category: 'Computer Science', phonetic: 'hash map' },
]
